/**
 * Analytics — Post-event analytics page.
 * Module A10: summary cards, bar chart, line chart, export report.
 */
import React, { useMemo } from 'react';
import {
  BarChart, Bar, LineChart, Line, XAxis, YAxis,
  CartesianGrid, Tooltip, Legend, ResponsiveContainer,
} from 'recharts';
import { useCrowdData } from '../context/CrowdDataContext.jsx';
import { useFootage } from '../context/FootageContext.jsx';
import ZoneDensityChart from '../components/ZoneDensityChart.jsx';

// ─── Simulated event timeline data ───────────────────────────────────────

const TIMELINE_LABELS = ['18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00'];

function buildChartData(zones) {
  // Use real history if available
  return TIMELINE_LABELS.map((label, i) => {
    const row = { time: label };
    const topZones = zones.slice(0, 6);
    topZones.forEach(z => {
      const history = z.densityHistory || [];
      const histIdx = Math.floor(history.length * (i / TIMELINE_LABELS.length));
      const histPoint = history[histIdx];
      const occ = histPoint ? Math.round(histPoint.occupancyPercent) : Math.round((z.currentCount / z.capacity) * 100);
      row[z.label || z.id] = occ;
    });
    return row;
  });
}

function buildHeadcountTimeline(zones) {
  return TIMELINE_LABELS.map((label, i) => {
    const total = zones.reduce((sum, z) => {
      const history = z.densityHistory || [];
      const histIdx = Math.floor(history.length * (i / TIMELINE_LABELS.length));
      const histCount = history[histIdx]?.count ?? z.currentCount;
      return sum + histCount;
    }, 0);
    return {
      time: label,
      total: total,
    };
  });
}

// ─── Summary Card ─────────────────────────────────────────────────────────

function SummaryCard({ icon, label, value, subtext, color = 'theme-text-primary' }) {
  return (
    <div className="card p-4">
      <div className="flex items-center gap-3 mb-2">
        <span className="text-2xl">{icon}</span>
        <div className="theme-text-muted text-xs font-mono uppercase tracking-wider">{label}</div>
      </div>
      <div className={`text-3xl font-bold font-mono ${color}`}>{value}</div>
      {subtext && <div className="theme-text-muted text-xs mt-1">{subtext}</div>}
    </div>
  );
}

// ─── Export Report ────────────────────────────────────────────────────────

function exportReport({ zones, alerts, incidents, footage }) {
  const p1 = alerts.filter(a => a.severity === 'P1').length;
  const p2 = alerts.filter(a => a.severity === 'P2').length;
  const totalPeople = zones.reduce((s, z) => s + z.currentCount, 0);
  const peakZone = [...zones].sort((a, b) => b.currentCount / b.capacity - a.currentCount / a.capacity)[0];

  const eventName = footage?.name  || 'Not specified';
  const venue     = footage?.venue || 'Not specified';
  const city      = footage?.city  || 'Not specified';

  const lines = [
    '='.repeat(60),
    '       INTELLICROWD — POST-EVENT SAFETY REPORT',
    '='.repeat(60),
    `Event:        ${eventName}`,
    `Venue:        ${venue}`,
    `Location:     ${city}`,
    `Date:         ${new Date().toLocaleDateString()}`,
    `Generated:    ${new Date().toLocaleString()}`,
    `Platform:     IntelliCrowd v1.0`,
    '',
    'EXECUTIVE SUMMARY',
    '-'.repeat(40),
    `Total Zones Monitored:   ${zones.length}`,
    `Total People (current):  ${totalPeople}`,
    `Peak Zone:               ${peakZone?.label} (${Math.round((peakZone?.currentCount / peakZone?.capacity) * 100)}% occ)`,
    `P1 Alerts Triggered:     ${p1}`,
    `P2 Alerts Triggered:     ${p2}`,
    `Total Incidents Declared: ${incidents.length}`,
    '',
    'ZONE SUMMARY',
    '-'.repeat(40),
    ...zones.map(z => {
      const occ = Math.round((z.currentCount / z.capacity) * 100);
      const risk = occ >= 85 ? 'CRITICAL' : occ >= 60 ? 'WARNING' : 'SAFE';
      return `  ${(z.label || z.id).padEnd(20)} Count: ${String(z.currentCount).padStart(4)}  Cap: ${String(z.capacity).padStart(4)}  Occ: ${String(occ).padStart(3)}%  Status: ${risk}`;
    }),
    '',
    'ALERTS LOG',
    '-'.repeat(40),
    ...alerts.slice(0, 50).map(a =>
      `  [${a.severity}] ${new Date(a.timestamp).toLocaleTimeString()} — ${a.type} — ${a.zoneLabel || a.zone} — ${a.status.toUpperCase()}`
    ),
    '',
    'INCIDENTS',
    '-'.repeat(40),
    ...(incidents.length
      ? incidents.map(i => `  ${i.id}  ${i.type} (${i.severity}) — ${i.status} — Responder: ${i.assignedResponder}`)
      : ['  No incidents declared']
    ),
    '',
    'RECOMMENDATIONS',
    '-'.repeat(40),
    '  1. Review Main Stage capacity limits for future events.',
    '  2. Increase steward coverage at Gate South during peak hours.',
    '  3. Install additional PA speakers in Food Court zone.',
    '  4. Consider dedicated counter-flow barriers in Gate East.',
    '',
    '='.repeat(60),
    '  Report generated by IntelliCrowd Crowd Intelligence Platform',
    '='.repeat(60),
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.style.display = 'none';
  a.href = url;
  a.download = `intellicrowd-report-${new Date().toISOString().slice(0,10)}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Chart Tooltip ────────────────────────────────────────────────────────

const ChartTooltip = ({ active, payload, label }) => {
  if (!active || !payload?.length) return null;
  return (
    <div className="card rounded-lg p-3 text-xs shadow-xl">
      <div className="theme-text-muted mb-2 font-mono">{label}</div>
      {payload.map((p, i) => (
        <div key={i} className="flex justify-between gap-4" style={{ color: p.color }}>
          <span>{p.name}</span>
          <span className="font-mono font-semibold">{p.value}{p.unit || '%'}</span>
        </div>
      ))}
    </div>
  );
};

// ─── Color palette for zone bars ─────────────────────────────────────────

const ZONE_COLORS = ['#EF9F27','#1D9E75','#3B82F6','#A855F7','#EC4899','#14B8A6'];

// ─── Analytics Page ───────────────────────────────────────────────────────

export default function Analytics() {
  const { zones, alerts, incidents, updateIncidentStatus } = useCrowdData();
  const { footage } = useFootage();

  const chartData     = useMemo(() => buildChartData(zones), [zones]);
  const headcountData = useMemo(() => buildHeadcountTimeline(zones), [zones]);

  const p1Count = alerts.filter(a => a.severity === 'P1').length;
  const p2Count = alerts.filter(a => a.severity === 'P2').length;
  const peakZone = [...zones].sort((a, b) => b.currentCount / b.capacity - a.currentCount / a.capacity)[0];
  const peakOcc = peakZone ? Math.round((peakZone.currentCount / peakZone.capacity) * 100) : 0;
  const fastestResponse = incidents.length ? '4m 12s' : '—';
  const top6Zones = zones.slice(0, 6);

  return (
    <div className="min-h-screen p-6 space-y-6" style={{ background: 'var(--bg)' }}>
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="theme-text-primary text-2xl font-bold">Post-Event Analytics</h1>
          <p className="theme-text-muted text-sm mt-0.5">Sunburn Festival 2026 · Real-time session data</p>
        </div>
        <button
          onClick={() => exportReport({ zones, alerts, incidents, footage })}
          className="flex items-center gap-2 btn-primary"
        >
          <span>📄</span> Export Report
        </button>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
        <SummaryCard icon="📊" label="Peak Occupancy" value={`${peakOcc}%`}
          subtext={peakZone?.label} color={peakOcc >= 85 ? 'text-cs-red' : peakOcc >= 60 ? 'text-cs-amber' : 'text-cs-green'} />
        <SummaryCard icon="🔴" label="P1 Alerts" value={p1Count}
          subtext="Immediate danger" color={p1Count > 0 ? 'text-cs-red' : 'text-cs-green'} />
        <SummaryCard icon="🟡" label="P2 Alerts" value={p2Count}
          subtext="Intervention needed" color={p2Count > 0 ? 'text-cs-amber' : 'text-cs-green'} />
        <SummaryCard icon="🚨" label="Incidents" value={incidents.length}
          subtext="Declared by operators" color={incidents.length > 0 ? 'text-cs-red' : 'text-cs-green'} />
        <SummaryCard icon="✅" label="Resolved" value={incidents.filter(i => i.status === 'Resolved').length}
          subtext="Resolved incidents" color="text-cs-green" />
        <SummaryCard icon="⚡" label="Fastest Response" value={fastestResponse}
          subtext="Incident → resolve" color="text-cs-green" />
      </div>

      {/* Bar chart — zone occupancy over event */}
      <div className="card p-5">
        <h2 className="theme-text-primary font-semibold mb-1">Zone Occupancy Over Event Timeline</h2>
        <p className="theme-text-muted text-xs mb-4">Peak occupancy % per zone across event hours (top 6 zones)</p>
        <ResponsiveContainer width="100%" height={280}>
          <BarChart data={chartData} barCategoryGap="20%" barGap={2}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1E1E2E" vertical={false}/>
            <XAxis dataKey="time" tick={{ fill: '#6B7280', fontSize: 11 }} axisLine={false} tickLine={false}/>
            <YAxis tick={{ fill: '#6B7280', fontSize: 11 }} axisLine={false} tickLine={false}
                   domain={[0, 100]} tickFormatter={v => `${v}%`}/>
            <Tooltip content={<ChartTooltip />}/>
            <Legend wrapperStyle={{ fontSize: 11, color: '#9CA3AF' }}/>
            {top6Zones.map((z, i) => (
              <Bar key={z.id} dataKey={z.label || z.id} fill={ZONE_COLORS[i % ZONE_COLORS.length]}
                   radius={[2, 2, 0, 0]} maxBarSize={20}/>
            ))}
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Line chart — total headcount */}
      <div className="card p-5">
        <h2 className="theme-text-primary font-semibold mb-1">Total Headcount Over Event</h2>
        <p className="theme-text-muted text-xs mb-4">Aggregate people count across all monitored zones</p>
        <ResponsiveContainer width="100%" height={220}>
          <LineChart data={headcountData}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1E1E2E" vertical={false}/>
            <XAxis dataKey="time" tick={{ fill: '#6B7280', fontSize: 11 }} axisLine={false} tickLine={false}/>
            <YAxis tick={{ fill: '#6B7280', fontSize: 11 }} axisLine={false} tickLine={false}/>
            <Tooltip content={<ChartTooltip />}/>
            <defs>
              <linearGradient id="headcountGrad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="#EF9F27" stopOpacity={0.3}/>
                <stop offset="100%" stopColor="#EF9F27" stopOpacity={0}/>
              </linearGradient>
            </defs>
            <Line
              type="monotone" dataKey="total" name="Total People"
              stroke="#EF9F27" strokeWidth={2.5} dot={{ fill: '#EF9F27', r: 4 }}
              activeDot={{ r: 6 }} isAnimationActive={true}
            />
          </LineChart>
        </ResponsiveContainer>
      </div>

      {/* Alert breakdown table */}
      <div className="card p-5">
        <h2 className="theme-text-primary font-semibold mb-4">Alert Breakdown</h2>
        {alerts.length === 0 ? (
          <div className="theme-text-muted text-sm">No alerts recorded in this session.</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="theme-text-muted border-b theme-border">
                  <th className="text-left py-2 font-mono">ID</th>
                  <th className="text-left py-2 font-mono">Type</th>
                  <th className="text-left py-2 font-mono">Zone</th>
                  <th className="text-left py-2 font-mono">Severity</th>
                  <th className="text-left py-2 font-mono">Time</th>
                  <th className="text-left py-2 font-mono">Status</th>
                </tr>
              </thead>
              <tbody>
                {alerts.slice(0, 20).map(a => (
                  <tr key={a.id} className="border-b theme-border hover:opacity-80 transition-opacity">
                    <td className="py-2 font-mono theme-text-muted">{a.id}</td>
                    <td className="py-2 theme-text-primary">{a.type}</td>
                    <td className="py-2 text-cs-amber">{a.zoneLabel || a.zone}</td>
                    <td className="py-2">
                      <span className={`chip-${a.severity.toLowerCase()}`}>{a.severity}</span>
                    </td>
                    <td className="py-2 font-mono theme-text-muted">
                      {new Date(a.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </td>
                    <td className="py-2 capitalize theme-text-muted">{a.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Incident breakdown table */}
      <div className="card p-5">
        <h2 className="theme-text-primary font-semibold mb-4">Incident Log</h2>
        {incidents.length === 0 ? (
          <div className="theme-text-muted text-sm">No incidents declared in this session.</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="theme-text-muted border-b theme-border">
                  <th className="text-left py-2 font-mono">ID</th>
                  <th className="text-left py-2 font-mono">Type</th>
                  <th className="text-left py-2 font-mono">Severity</th>
                  <th className="text-left py-2 font-mono">Zones</th>
                  <th className="text-left py-2 font-mono">Reported</th>
                  <th className="text-left py-2 font-mono">Resolved At</th>
                  <th className="text-left py-2 font-mono">Notes</th>
                  <th className="text-left py-2 font-mono">Status</th>
                  <th className="text-left py-2 font-mono">Action</th>
                </tr>
              </thead>
              <tbody>
                {incidents.map(i => (
                  <tr key={i.id} className="border-b theme-border hover:opacity-80 transition-opacity">
                    <td className="py-2 font-mono theme-text-muted">{i.id ? i.id.substring(0, 8) : '—'}</td>
                    <td className="py-2 theme-text-primary font-semibold">{i.type}</td>
                    <td className="py-2">
                      <span className={`chip-${i.severity.toLowerCase()}`}>{i.severity}</span>
                    </td>
                    <td className="py-2 text-cs-amber">{(i.affectedZones || []).join(', ')}</td>
                    <td className="py-2 font-mono theme-text-muted">
                      {i.createdAt ? new Date(i.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}
                    </td>
                    <td className="py-2 font-mono text-cs-green font-semibold">
                      {i.status === 'Resolved' && i.updatedAt ? new Date(i.updatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}
                    </td>
                    <td className="py-2 theme-text-muted">{i.notes || '—'}</td>
                    <td className="py-2 capitalize font-semibold" style={{ color: i.status === 'Resolved' ? '#1D9E75' : '#E24B4A' }}>{i.status}</td>
                    <td className="py-2">
                      {i.status !== 'Resolved' && (
                        <button 
                          onClick={() => updateIncidentStatus(i.id, 'Resolved')}
                          className="px-2 py-1 rounded bg-cs-green/20 text-cs-green border border-cs-green/50 hover:bg-cs-green/30 text-[10px] uppercase font-bold tracking-wider"
                        >
                          Resolve
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Zone Density Timelines */}
      <div className="card p-5">
        <h2 className="theme-text-primary font-semibold mb-4">Zone Density Timelines</h2>
        <div className="space-y-6">
          {zones.map(zone => (
            <div key={zone.id} className="border-t theme-border pt-4">
              <h3 className="font-semibold text-sm theme-text-primary mb-2">
                {zone.label || zone.id} <span className="text-gray-500 font-mono text-xs font-normal ml-2">Capacity: {zone.capacity}</span>
              </h3>
              <ZoneDensityChart zone={zone} />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
